controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# nelmio_api_doc:
#     resource: "@NelmioApiDocBundle/Resources/config/routing/swagger.yaml"
#     prefix:   /api/doc
